### ISSUE TITLE
Contribute to upstream

### ISSUE THREAD

**Issue by digitalkaoz** [syseleven/designate-certmanager-webhook#3]
Hey, thanks for this! Are you willing to contribute this back to the upstream cert-manager or publish this to the helm repository?

**Comment by frittenlab** [comment]
We would like to do this. But I don't think it will be accepted:

https://cert-manager.io/docs/contributing/dns-providers/

The jetstack developers said that this is to much work for them to add all provider plugins. We could add it to an additional helm repository if you like.

**Comment by digitalkaoz** [comment]
That would be awesome!
