### ISSUE TITLE
Support for 1.15+ cert-manager resources

### ISSUE THREAD

**Issue by ledsole** [syseleven/designate-certmanager-webhook#4]
I received the following while testing this out:

$ helm install designate-certmanager --namespace=cert-manager designate-certmanager-webhook
Error: failed to download "designate-certmanager-webhook" (hint: running `helm repo update` may help)

I'm running kubernetes 1.17 with the following crds:
https://github.com/jetstack/cert-manager/releases/download/v0.15.1/cert-manager.crds.yaml

I suspect this is looking for the legacy crds?

EDIT: I pasted the wrong error above. The error I was actually getting was due the naming change that ocurred in cert-manager crds v0.11.0

**Comment by frittenlab** [comment]
Did you clone the repository first ? This chart is not part of the official helm charts. Looking at the error message. I would say that the repository is missing.

**Comment by frittenlab** [comment]
This should do the trick:

For now, we do not host a chart repository. To use this chart, you must clone this repository. Edit the values.yaml file and add your OpenStack settings if you did not create the secret before. Then you can install the helm chart with the command:

helm install --name designate-certmanager --namespace=cert-manager designate-certmanager-webhook

**Comment by ledsole** [comment]
I did clone the repo and I ran helm from the directory where designate-certmanager-webhook was.  I got it to install after replacing the api crd values from "certmanager.k8s.io/v1alpha1" to  "cert-manager.io/v1alpha2"

I still need to test if it actually works. Will let you know.

**Comment by ledsole** [comment]
So I got it to install and it sees my openstack credentials and designate endpoint.  However, when I try to issue a certificate, the challenge get stuck in a pending state and I get the following:

"error"="the server is currently unable to handle the request (post designatedns.acme.syseleven.de)" 

I think this might be due to my version of cert-manager/kubernetes.  @frittenlab What is the latest version that this will work on?

**Comment by frittenlab** [comment]
At the moment we are using this version of the cert-manager:

quay.io/jetstack/cert-manager-controller:v0.10.1

We are planing on upgrading shortly. The TLS handshake errors in you cluster don't look right. Are all of you API endpoints reachable? At the moment we are using external dns:

https://github.com/kubernetes-sigs/external-dns

and the cert-manager with designate.

**Comment by ledsole** [comment]
Perfect.  Thank you, I got it working with with a fresh installation of cert-manager v0.10.1 with no problem.

Also, I apologize for the confusion as I pasted the wrong error on my first post.  The issue I originally had was due to the change in the name of cert-manager crds that happened in v0.11.0 ()I used v0.15.0 in my first attempt:

https://github.com/jetstack/cert-manager/releases/tag/v0.11.0

Renaming our API group from certmanager.k8s.io to cert-manager.io
Bumping the API version from v1alpha1 to v1alpha2

So that was causing the chart installation to fail for me and switching to 0.10.1 which uses the older names worked.

**Comment by isantospardo** [comment]
Support newer versions of cert-manager would be great. 👍

**Comment by frittenlab** [comment]
@isantospardo We will offer support for the current versions of the cert-manager shortly.

**Comment by frittenlab** [comment]
We just added the new release for cert-manager 0.15.x would be great if you can give it a try.
